require "./spec_helper"

# Operation used to verify the per-subclass `.with` (generated by
# `__build_with` in `operation.cr`) accepts every valid kwargs shape and
# preserves the pre-existing partial-application behavior. Negative cases
# (unknown keys) are compile errors and so cannot be exercised here -- see
# `examples/should_fail_unknown_kw.cr` for the manual build-time check.
class WithValidationOp < OperationCr::Operation
  param name : String
  param greeting : String = "Hello"
  param suffix : String = "!"

  def perform
    "#{greeting}, #{name}#{suffix}"
  end
end

describe "Operation.with key validation" do
  it "accepts a single valid required key" do
    WithValidationOp.with(name: "Ada").call.should eq "Hello, Ada!"
  end

  it "accepts a single valid optional key" do
    partial = WithValidationOp.with(greeting: "Hi")
    partial.call(name: "Ada").should eq "Hi, Ada!"
  end

  it "accepts multiple valid keys at once" do
    WithValidationOp.with(name: "Ada", greeting: "Hi", suffix: "?").call.should eq "Hi, Ada?"
  end

  it "accepts an empty .with() call" do
    WithValidationOp.with.call(name: "Ada").should eq "Hello, Ada!"
  end

  it "returns a PartiallyApplied of the right operation type" do
    partial = WithValidationOp.with(name: "Ada")
    partial.should be_a(OperationCr::PartiallyApplied(WithValidationOp, Tuple(), NamedTuple(name: String)))
  end

  it "preserves chained-.with behaviour (chained .with goes through PartiallyApplied)" do
    step1 = WithValidationOp.with(greeting: "Howdy")
    step2 = step1.with(name: "Ada")
    step2.call.should eq "Howdy, Ada!"
  end
end
